### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by jts272** [jts272/My-First-Agile-Project#5]
As a **site admin** I can **add new images to the gallery** so that **I can attract users to different events**
  
### Acceptance Criteria:
  
  - New images can be added to the gallery, with the newest image first
  - Descriptions can be added to the images
  - Images can be separated by track type
  - Link included to sign up page with track type pre-checked
  
### Tasks:
  
  - [ ] Ensure newest image is inserted first into the gallery
  - [ ] Images have descriptive text added
  - [ ] Separate gallery by track type
  - [ ] Include link at bottom of respective gallery to sign up page, with appropriate button checked
