### ISSUE TITLE
USER STORY: User poll to establish new running events

### ISSUE THREAD

**Issue by jts272** [jts272/My-First-Agile-Project#6]
As a **site user** I can **vote on new running arrangements** so that **I can try new running challenges**
  
### Acceptance Criteria:
  
  - Poll is visible on homepage
  - Signed-in users can vote on criteria for new events
  - Comment section is available for further user input
  
### Tasks:
  
  - [ ] Add poll to homepage
  - [ ] Give users voting rights
  - [ ] Ensure poll validation (required radio buttons)
  - [ ] Add comment section and allow signed-in users to comment
